config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'

  get '/about', to: 'about#index'

  get 'users/new', to: 'users#new', as: :new_user
  post 'users', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  resources :products, only: [:index, :show]
  resources :categories, only: [:index, :show]

  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  resources :orders, only: [:create, :show]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, except: [:edit, :update, :destroy]
  end

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  http_basic_authenticate_with name: ENV["ADMIN_USERNAME"], password: ENV["ADMIN_PASSWORD"]
  def show
    @product_count = Product.count
    @category_count = Category.count
    @products = Product.all
    @categories = Category.all
  end
end

app/views/admin/dashboard/show.html.erb
<section class="admin-dashboard">
  <header class="page-header">
    <h1>Admin &raquo; Dashboard</h1>
  </header>

  <div class="panel panel-default products">
    <div class="table-wrapper">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Products in Database: <%= @product_count %></th>
          </tr>
        </thead>
        <tbody>
          <% @products.each do |product| %>
            <tr>
              <td>
                <%= link_to product.name, product_path(product) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Categories in Database: <%= @category_count %></th>
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |category| %>
            <tr>
              <td>
                <%= link_to category.name, category_path(category) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>